version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  app:
    build: .
    environment:
      APP_JWT_SECRET: 2epyeGrlzD9h2AbBC4KIOK7BPMnwaBHe
      APP_DATABASE_URL: postgres://desafio_go:desafio_go@db/desafio_go?sslmode=disable
    ports:
      - 9999:9999
